// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPhbkf9qJG1Ji2Bi6K-VMYq_Q5rRFh5Ug',
    appId: '1:114144707560:web:1f9c26bf9e17e9350a1a5d',
    messagingSenderId: '114144707560',
    projectId: 'allcare-e00f7',
    authDomain: 'allcare-e00f7.firebaseapp.com',
    storageBucket: 'allcare-e00f7.firebasestorage.app',
    measurementId: 'G-Z25KDRLB44',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDg6ylbLMkw5me7NM35iPKVEQ3PcZhtgdQ',
    appId: '1:114144707560:android:e22f0dccb78a6dd40a1a5d',
    messagingSenderId: '114144707560',
    projectId: 'allcare-e00f7',
    storageBucket: 'allcare-e00f7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7uXDAIhlunas29HDEsUW-i7vBHyZQJcQ',
    appId: '1:114144707560:ios:eb51dda2b9aad0eb0a1a5d',
    messagingSenderId: '114144707560',
    projectId: 'allcare-e00f7',
    storageBucket: 'allcare-e00f7.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7uXDAIhlunas29HDEsUW-i7vBHyZQJcQ',
    appId: '1:114144707560:ios:eb51dda2b9aad0eb0a1a5d',
    messagingSenderId: '114144707560',
    projectId: 'allcare-e00f7',
    storageBucket: 'allcare-e00f7.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPhbkf9qJG1Ji2Bi6K-VMYq_Q5rRFh5Ug',
    appId: '1:114144707560:web:5c1a977707a9969b0a1a5d',
    messagingSenderId: '114144707560',
    projectId: 'allcare-e00f7',
    authDomain: 'allcare-e00f7.firebaseapp.com',
    storageBucket: 'allcare-e00f7.firebasestorage.app',
    measurementId: 'G-9JRFXVETDR',
  );
}
